export const LOGIN_CINEMATIC_TOTAL_MS = 7200;
export const LOGIN_CINEMATIC_HANDOFF_RATIO = 0.7;
export const LOGIN_CINEMATIC_NAVIGATION_DELAY_MS = Math.round(
  LOGIN_CINEMATIC_TOTAL_MS * LOGIN_CINEMATIC_HANDOFF_RATIO,
);

export const LOGIN_CINEMATIC_WIPE_BUFFER_MS = 420;
export const LOGIN_CINEMATIC_DASHBOARD_WIPE_MS = Math.ceil(
  LOGIN_CINEMATIC_TOTAL_MS * (1 - LOGIN_CINEMATIC_HANDOFF_RATIO),
) + LOGIN_CINEMATIC_WIPE_BUFFER_MS;

export const LOGIN_CINEMATIC_DROPLET_COUNT = 26;
