// Source of truth for the global ingredient catalog.
//
// Edit this file and re-run `node scripts/generate-ingredient-catalog-migration.mjs`
// to regenerate the seed migration. Keeping the data here (rather than hand-writing
// SQL) keeps the catalog easy to extend and the migration deterministic.
//
// Ingredient tuple: [name, emoji, defaultUnit, aliases?, allergens?]
// Allergen codes (EU 14): gluten, crustaceans, eggs, fish, peanuts, soy, milk,
// nuts, celery, mustard, sesame, sulphites, lupin, molluscs.

export const categories = [
  { id: 'vegetables', name: 'Grönsaker', emoji: '🥬', sortOrder: 10 },
  { id: 'fruit', name: 'Frukt & bär', emoji: '🍎', sortOrder: 20 },
  { id: 'herbs', name: 'Örter & kryddor', emoji: '🌿', sortOrder: 30 },
  { id: 'meat', name: 'Kött & chark', emoji: '🥩', sortOrder: 40 },
  { id: 'poultry', name: 'Fågel', emoji: '🍗', sortOrder: 50 },
  { id: 'seafood', name: 'Fisk & skaldjur', emoji: '🦐', sortOrder: 60 },
  { id: 'dairy', name: 'Mejeri & ost', emoji: '🧀', sortOrder: 70 },
  { id: 'bread', name: 'Bröd & bageri', emoji: '🍞', sortOrder: 80 },
  { id: 'grains', name: 'Spannmål & pasta', emoji: '🌾', sortOrder: 90 },
  { id: 'legumes', name: 'Baljväxter & vegoprotein', emoji: '🫘', sortOrder: 100 },
  { id: 'nuts', name: 'Nötter & frön', emoji: '🥜', sortOrder: 110 },
  { id: 'mushrooms', name: 'Svamp', emoji: '🍄', sortOrder: 120 },
  { id: 'sauces', name: 'Såser & dressing', emoji: '🥫', sortOrder: 130 },
  { id: 'condiments', name: 'Smaksättare & skafferi', emoji: '🧂', sortOrder: 140 },
  { id: 'oils', name: 'Oljor & fetter', emoji: '🫒', sortOrder: 150 },
  { id: 'baking', name: 'Bak & sötning', emoji: '🍯', sortOrder: 160 },
  { id: 'beverages', name: 'Dryck', emoji: '🥤', sortOrder: 170 },
  { id: 'other', name: 'Övrigt', emoji: '🍽️', sortOrder: 999 },
];

export const ingredients = {
  vegetables: [
    ['Tomat', '🍅', 'st', ['tomato']],
    ['Bifftomat', '🍅', 'skiva', ['beef tomato', 'bifftomat']],
    ['Körsbärstomat', '🍅', 'st', ['cherry tomato']],
    ['Soltorkad tomat', '🍅', 'g', ['sundried tomato']],
    ['Gurka', '🥒', 'skiva', ['cucumber']],
    ['Isbergssallad', '🥬', 'blad', ['iceberg lettuce', 'sallad']],
    ['Ruccola', '🌿', 'g', ['rocket', 'arugula']],
    ['Babyspenat', '🥬', 'g', ['spinach', 'spenat']],
    ['Grönkål', '🥬', 'g', ['kale']],
    ['Vitkål', '🥬', 'g', ['cabbage']],
    ['Rödkål', '🥬', 'g', ['red cabbage']],
    ['Morot', '🥕', 'g', ['carrot']],
    ['Rödlök', '🧅', 'ring', ['red onion']],
    ['Gul lök', '🧅', 'g', ['onion', 'yellow onion']],
    ['Vit lök', '🧅', 'g', ['white onion']],
    ['Vitlök', '🧄', 'klyfta', ['garlic']],
    ['Salladslök', '🌿', 'st', ['spring onion', 'scallion']],
    ['Purjolök', '🥬', 'g', ['leek']],
    ['Schalottenlök', '🧅', 'st', ['shallot']],
    ['Röd paprika', '🫑', 'g', ['red pepper', 'bell pepper']],
    ['Gul paprika', '🫑', 'g', ['yellow pepper']],
    ['Chili', '🌶️', 'st', ['chili']],
    ['Jalapeño', '🌶️', 'st', ['jalapeno']],
    ['Aubergine', '🍆', 'g', ['eggplant', 'aubergine']],
    ['Zucchini', '🥒', 'g', ['zucchini', 'courgette']],
    ['Broccoli', '🥦', 'g', ['broccoli']],
    ['Blomkål', '🥦', 'g', ['cauliflower']],
    ['Majs', '🌽', 'dl', ['corn', 'sweetcorn']],
    ['Ärtor', '🫛', 'dl', ['peas']],
    ['Sockerärter', '🫛', 'g', ['snow peas', 'sugar snap']],
    ['Avokado', '🥑', 'st', ['avocado']],
    ['Potatis', '🥔', 'g', ['potato']],
    ['Sötpotatis', '🍠', 'g', ['sweet potato']],
    ['Rödbeta', '🫐', 'g', ['beetroot']],
    ['Selleri', '🥬', 'g', ['celery'], ['celery']],
    ['Sparris', '🥬', 'st', ['asparagus']],
    ['Rädisa', '🌶️', 'st', ['radish']],
    ['Pumpa', '🎃', 'g', ['pumpkin']],
    ['Butternutpumpa', '🎃', 'g', ['butternut squash']],
    ['Pak choi', '🥬', 'st', ['bok choy', 'pak choi']],
    ['Oliver', '🫒', 'st', ['olives']],
    ['Inlagd gurka', '🥒', 'skiva', ['pickles']],
    ['Kimchi', '🥬', 'g', ['kimchi']],
    ['Surkål', '🥬', 'g', ['sauerkraut']],
    ['Picklad rödlök', '🧅', 'g', ['pickled red onion']],
  ],
  fruit: [
    ['Äpple', '🍎', 'st', ['apple']],
    ['Päron', '🍐', 'st', ['pear']],
    ['Banan', '🍌', 'st', ['banana']],
    ['Apelsin', '🍊', 'st', ['orange']],
    ['Citron', '🍋', 'st', ['lemon']],
    ['Lime', '🍋', 'st', ['lime']],
    ['Mango', '🥭', 'st', ['mango']],
    ['Ananas', '🍍', 'g', ['pineapple']],
    ['Vindruvor', '🍇', 'g', ['grapes']],
    ['Jordgubbar', '🍓', 'g', ['strawberry']],
    ['Blåbär', '🫐', 'g', ['blueberry']],
    ['Hallon', '🍓', 'g', ['raspberry']],
    ['Lingon', '🫐', 'dl', ['lingonberry']],
    ['Granatäpple', '🍎', 'st', ['pomegranate']],
    ['Fikon', '🍈', 'st', ['fig']],
    ['Dadlar', '🍯', 'st', ['dates']],
    ['Russin', '🍇', 'dl', ['raisins']],
    ['Kiwi', '🥝', 'st', ['kiwi']],
    ['Persika', '🍑', 'st', ['peach']],
    ['Vattenmelon', '🍉', 'g', ['watermelon']],
    ['Kokos', '🥥', 'g', ['coconut']],
    ['Passionsfrukt', '🍈', 'st', ['passion fruit']],
  ],
  herbs: [
    ['Basilika', '🌿', 'nypa', ['basil']],
    ['Persilja', '🌿', 'nypa', ['parsley']],
    ['Koriander', '🌿', 'nypa', ['cilantro', 'coriander']],
    ['Dill', '🌿', 'nypa', ['dill']],
    ['Gräslök', '🌿', 'nypa', ['chives']],
    ['Timjan', '🌿', 'nypa', ['thyme']],
    ['Rosmarin', '🌿', 'nypa', ['rosemary']],
    ['Oregano', '🌿', 'nypa', ['oregano']],
    ['Mynta', '🌿', 'nypa', ['mint']],
    ['Ingefära', '🫚', 'g', ['ginger']],
    ['Gurkmeja', '🌿', 'tsk', ['turmeric']],
    ['Spiskummin', '🌿', 'tsk', ['cumin']],
    ['Paprikapulver', '🌶️', 'tsk', ['paprika']],
    ['Svartpeppar', '🧂', 'nypa', ['black pepper']],
    ['Kanel', '🌿', 'tsk', ['cinnamon']],
    ['Kardemumma', '🌿', 'tsk', ['cardamom']],
    ['Saffran', '🌿', 'g', ['saffron']],
    ['Chiliflingor', '🌶️', 'nypa', ['chili flakes']],
    ['Curry', '🌿', 'tsk', ['curry']],
    ['Garam masala', '🌿', 'tsk', ['garam masala']],
  ],
  meat: [
    ['Nötfärs', '🥩', 'g', ['ground beef', 'minced beef']],
    ['Ryggbiff', '🥩', 'g', ['sirloin', 'beef']],
    ['Oxfilé', '🥩', 'g', ['beef tenderloin']],
    ['Högrev', '🥩', 'g', ['chuck']],
    ['Fläskkarré', '🥩', 'g', ['pork shoulder']],
    ['Fläskfilé', '🥩', 'g', ['pork tenderloin']],
    ['Bacon', '🥓', 'skiva', ['bacon']],
    ['Skinka', '🍖', 'skiva', ['ham']],
    ['Lufttorkad skinka', '🍖', 'skiva', ['prosciutto', 'serrano']],
    ['Salami', '🍖', 'skiva', ['salami']],
    ['Chorizo', '🌭', 'g', ['chorizo']],
    ['Pancetta', '🥓', 'g', ['pancetta']],
    ['Lammfärs', '🥩', 'g', ['ground lamb']],
    ['Korv', '🌭', 'st', ['sausage']],
    ['Köttbullar', '🍖', 'st', ['meatballs']],
    ['Pulled pork', '🍖', 'g', ['pulled pork']],
    ['Mortadella', '🍖', 'skiva', ['mortadella']],
  ],
  poultry: [
    ['Kycklingfilé', '🍗', 'g', ['chicken breast', 'kyckling']],
    ['Kycklinglårfilé', '🍗', 'g', ['chicken thigh']],
    ['Kycklingvingar', '🍗', 'st', ['chicken wings']],
    ['Kalkon', '🦃', 'g', ['turkey']],
    ['Anka', '🦆', 'g', ['duck']],
    ['Kycklingfärs', '🍗', 'g', ['ground chicken']],
  ],
  seafood: [
    ['Lax', '🐟', 'g', ['salmon'], ['fish']],
    ['Rökt lax', '🐟', 'g', ['smoked salmon'], ['fish']],
    ['Gravad lax', '🐟', 'g', ['cured salmon'], ['fish']],
    ['Torsk', '🐟', 'g', ['cod'], ['fish']],
    ['Tonfisk', '🐟', 'g', ['tuna'], ['fish']],
    ['Räkor', '🦐', 'g', ['shrimp', 'prawns'], ['crustaceans']],
    ['Kräftor', '🦞', 'st', ['crayfish'], ['crustaceans']],
    ['Krabba', '🦀', 'g', ['crab'], ['crustaceans']],
    ['Hummer', '🦞', 'st', ['lobster'], ['crustaceans']],
    ['Musslor', '🦪', 'g', ['mussels'], ['molluscs']],
    ['Ostron', '🦪', 'st', ['oysters'], ['molluscs']],
    ['Bläckfisk', '🦑', 'g', ['squid', 'calamari'], ['molluscs']],
    ['Sill', '🐟', 'g', ['herring'], ['fish']],
    ['Ansjovis', '🐟', 'st', ['anchovy'], ['fish']],
    ['Sardiner', '🐟', 'st', ['sardines'], ['fish']],
    ['Surimi', '🦀', 'st', ['surimi'], ['fish', 'crustaceans']],
  ],
  dairy: [
    ['Cheddar', '🧀', 'skiva', ['cheddar'], ['milk']],
    ['Mozzarella', '🧀', 'g', ['mozzarella'], ['milk']],
    ['Parmesan', '🧀', 'g', ['parmesan'], ['milk']],
    ['Fetaost', '🧀', 'g', ['feta'], ['milk']],
    ['Halloumi', '🧀', 'g', ['halloumi'], ['milk']],
    ['Brie', '🧀', 'skiva', ['brie'], ['milk']],
    ['Gorgonzola', '🧀', 'g', ['gorgonzola', 'blue cheese'], ['milk']],
    ['Getost', '🧀', 'g', ['goat cheese'], ['milk']],
    ['Grädde', '🥛', 'dl', ['cream'], ['milk']],
    ['Crème fraiche', '🥛', 'msk', ['creme fraiche'], ['milk']],
    ['Smör', '🧈', 'g', ['butter'], ['milk']],
    ['Mjölk', '🥛', 'dl', ['milk'], ['milk']],
    ['Turkisk yoghurt', '🥛', 'dl', ['turkish yogurt'], ['milk']],
    ['Ägg', '🥚', 'st', ['egg'], ['eggs']],
    ['Ricotta', '🧀', 'g', ['ricotta'], ['milk']],
    ['Mascarpone', '🧀', 'g', ['mascarpone'], ['milk']],
    ['Keso', '🧀', 'dl', ['cottage cheese'], ['milk']],
    ['Färskost', '🧀', 'msk', ['cream cheese'], ['milk']],
    ['Västerbottensost', '🧀', 'g', ['vasterbotten cheese'], ['milk']],
  ],
  bread: [
    ['Baguette', '🥖', 'st', ['baguette'], ['gluten']],
    ['Surdegsbröd', '🍞', 'skiva', ['sourdough'], ['gluten']],
    ['Ciabatta', '🍞', 'st', ['ciabatta'], ['gluten']],
    ['Focaccia', '🍞', 'bit', ['focaccia'], ['gluten']],
    ['Bagel', '🥯', 'st', ['bagel'], ['gluten']],
    ['Pitabröd', '🥙', 'st', ['pita'], ['gluten']],
    ['Tortilla', '🌯', 'st', ['tortilla', 'wrap'], ['gluten']],
    ['Naan', '🫓', 'st', ['naan'], ['gluten']],
    ['Rågbröd', '🍞', 'skiva', ['rye bread'], ['gluten']],
    ['Knäckebröd', '🍘', 'st', ['crispbread'], ['gluten']],
    ['Hamburgerbröd', '🍔', 'st', ['burger bun'], ['gluten']],
    ['Croissant', '🥐', 'st', ['croissant'], ['gluten', 'milk']],
  ],
  grains: [
    ['Spaghetti', '🍝', 'g', ['spaghetti'], ['gluten']],
    ['Penne', '🍝', 'g', ['penne'], ['gluten']],
    ['Tagliatelle', '🍝', 'g', ['tagliatelle'], ['gluten']],
    ['Lasagneplattor', '🍝', 'st', ['lasagne'], ['gluten']],
    ['Makaroner', '🍝', 'g', ['macaroni'], ['gluten']],
    ['Ris', '🍚', 'dl', ['rice']],
    ['Jasminris', '🍚', 'dl', ['jasmine rice']],
    ['Basmatiris', '🍚', 'dl', ['basmati rice']],
    ['Risottoris', '🍚', 'dl', ['arborio rice', 'risotto']],
    ['Quinoa', '🌾', 'dl', ['quinoa']],
    ['Couscous', '🌾', 'dl', ['couscous'], ['gluten']],
    ['Bulgur', '🌾', 'dl', ['bulgur'], ['gluten']],
    ['Havregryn', '🌾', 'dl', ['oats']],
    ['Nudlar', '🍜', 'g', ['noodles'], ['gluten']],
    ['Risnudlar', '🍜', 'g', ['rice noodles']],
    ['Gnocchi', '🥔', 'g', ['gnocchi'], ['gluten']],
  ],
  legumes: [
    ['Kikärtor', '🫘', 'dl', ['chickpeas']],
    ['Svarta bönor', '🫘', 'dl', ['black beans']],
    ['Kidneybönor', '🫘', 'dl', ['kidney beans']],
    ['Vita bönor', '🫘', 'dl', ['white beans']],
    ['Röda linser', '🫘', 'dl', ['red lentils']],
    ['Gröna linser', '🫘', 'dl', ['green lentils']],
    ['Edamame', '🫛', 'dl', ['edamame'], ['soy']],
    ['Tofu', '🧈', 'g', ['tofu'], ['soy']],
    ['Tempeh', '🧈', 'g', ['tempeh'], ['soy']],
    ['Falafel', '🧆', 'st', ['falafel']],
    ['Hummus', '🫙', 'msk', ['hummus'], ['sesame']],
  ],
  nuts: [
    ['Mandel', '🌰', 'g', ['almonds'], ['nuts']],
    ['Valnötter', '🌰', 'g', ['walnuts'], ['nuts']],
    ['Cashewnötter', '🥜', 'g', ['cashews'], ['nuts']],
    ['Hasselnötter', '🌰', 'g', ['hazelnuts'], ['nuts']],
    ['Pinjenötter', '🌰', 'g', ['pine nuts'], ['nuts']],
    ['Pistage', '🥜', 'g', ['pistachio'], ['nuts']],
    ['Jordnötter', '🥜', 'g', ['peanuts'], ['peanuts']],
    ['Solrosfrön', '🌻', 'msk', ['sunflower seeds']],
    ['Pumpafrön', '🎃', 'msk', ['pumpkin seeds']],
    ['Sesamfrön', '🌰', 'msk', ['sesame seeds'], ['sesame']],
    ['Chiafrön', '🌱', 'msk', ['chia seeds']],
    ['Kokosflingor', '🥥', 'dl', ['coconut flakes']],
  ],
  mushrooms: [
    ['Champinjoner', '🍄', 'g', ['mushrooms', 'button mushroom']],
    ['Kantareller', '🍄', 'g', ['chanterelles']],
    ['Karljohan', '🍄', 'g', ['porcini']],
    ['Shiitake', '🍄', 'g', ['shiitake']],
    ['Portabello', '🍄', 'st', ['portobello']],
    ['Ostronskivling', '🍄', 'g', ['oyster mushroom']],
    ['Tryffel', '🍄', 'g', ['truffle']],
  ],
  sauces: [
    ['Tomatsås', '🥫', 'dl', ['tomato sauce']],
    ['Pizzasås', '🥫', 'dl', ['pizza sauce']],
    ['Pesto', '🥫', 'msk', ['pesto'], ['nuts', 'milk']],
    ['Béarnaisesås', '🥫', 'dl', ['bearnaise'], ['eggs', 'milk']],
    ['Aioli', '🧄', 'msk', ['aioli'], ['eggs']],
    ['Vitlökssås', '🧄', 'msk', ['garlic sauce'], ['eggs']],
    ['Sweet chili', '🌶️', 'msk', ['sweet chili']],
    ['Sojasås', '🥫', 'msk', ['soy sauce'], ['soy', 'gluten']],
    ['Teriyaki', '🥫', 'msk', ['teriyaki'], ['soy', 'gluten']],
    ['Sriracha', '🌶️', 'tsk', ['sriracha']],
    ['BBQ-sås', '🥫', 'msk', ['bbq sauce']],
    ['Ketchup', '🍅', 'msk', ['ketchup']],
    ['Senap', '🌭', 'tsk', ['mustard'], ['mustard']],
    ['Majonnäs', '🥫', 'msk', ['mayonnaise', 'mayo'], ['eggs']],
    ['Tzatziki', '🥒', 'msk', ['tzatziki'], ['milk']],
    ['Salsa', '🍅', 'msk', ['salsa']],
    ['Guacamole', '🥑', 'msk', ['guacamole']],
    ['Fisksås', '🐟', 'tsk', ['fish sauce'], ['fish']],
    ['Hoisin', '🥫', 'msk', ['hoisin'], ['soy', 'gluten']],
    ['Tahini', '🥫', 'msk', ['tahini'], ['sesame']],
  ],
  condiments: [
    ['Salt', '🧂', 'nypa', ['salt']],
    ['Flingsalt', '🧂', 'nypa', ['flake salt']],
    ['Vitlökspulver', '🧄', 'tsk', ['garlic powder']],
    ['Bakpulver', '🧂', 'tsk', ['baking powder']],
    ['Jäst', '🍞', 'g', ['yeast']],
    ['Balsamvinäger', '🍾', 'msk', ['balsamic'], ['sulphites']],
    ['Äppelcidervinäger', '🍾', 'msk', ['apple cider vinegar'], ['sulphites']],
    ['Grönsaksbuljong', '🥫', 'tärning', ['vegetable stock'], ['celery']],
    ['Kycklingbuljong', '🥫', 'tärning', ['chicken stock'], ['celery']],
    ['Tomatpuré', '🥫', 'msk', ['tomato paste']],
    ['Krossade tomater', '🥫', 'dl', ['crushed tomatoes']],
    ['Kapris', '🫙', 'msk', ['capers']],
    ['Nori', '🍙', 'ark', ['nori', 'seaweed']],
    ['Misopasta', '🥣', 'msk', ['miso'], ['soy']],
    ['Panko', '🍞', 'dl', ['panko'], ['gluten']],
  ],
  oils: [
    ['Olivolja', '🫒', 'msk', ['olive oil']],
    ['Rapsolja', '🌻', 'msk', ['rapeseed oil', 'canola']],
    ['Sesamolja', '🌰', 'tsk', ['sesame oil'], ['sesame']],
    ['Kokosolja', '🥥', 'msk', ['coconut oil']],
    ['Tryffelolja', '🍄', 'tsk', ['truffle oil']],
    ['Margarin', '🧈', 'g', ['margarine']],
  ],
  baking: [
    ['Vetemjöl', '🌾', 'dl', ['wheat flour', 'flour'], ['gluten']],
    ['Mandelmjöl', '🌰', 'dl', ['almond flour'], ['nuts']],
    ['Strösocker', '🍬', 'dl', ['sugar']],
    ['Farinsocker', '🍯', 'dl', ['brown sugar']],
    ['Florsocker', '🍬', 'dl', ['powdered sugar']],
    ['Honung', '🍯', 'msk', ['honey']],
    ['Lönnsirap', '🍯', 'msk', ['maple syrup']],
    ['Kakao', '🍫', 'msk', ['cocoa']],
    ['Mörk choklad', '🍫', 'g', ['dark chocolate'], ['milk', 'soy']],
    ['Vaniljsocker', '🍦', 'tsk', ['vanilla sugar']],
  ],
  beverages: [
    ['Apelsinjuice', '🧃', 'dl', ['orange juice']],
    ['Äppeljuice', '🧃', 'dl', ['apple juice']],
    ['Cola', '🥤', 'dl', ['cola']],
    ['Kaffe', '☕', 'dl', ['coffee']],
    ['Espresso', '☕', 'shot', ['espresso']],
    ['Te', '🍵', 'dl', ['tea']],
    ['Havredryck', '🥛', 'dl', ['oat milk'], ['gluten']],
    ['Mineralvatten', '💧', 'dl', ['sparkling water']],
    ['Rödvin', '🍷', 'dl', ['red wine'], ['sulphites']],
    ['Vitvin', '🍷', 'dl', ['white wine'], ['sulphites']],
  ],
};
