// Bak & sötning. Tuple: [name, emoji?, defaultUnit?, aliases?, allergens?]
export default {
  category: 'baking',
  items: [
    ['Vetemjöl', '🌾', 'dl', ['wheat flour', 'flour'], ['gluten']],
    ['Vetemjöl special', '🌾', 'dl', ['strong flour'], ['gluten']],
    ['Durumvete', '🌾', 'dl', ['durum'], ['gluten']],
    ['Dinkelmjöl', '🌾', 'dl', ['spelt flour'], ['gluten']],
    ['Rågmjöl', '🌾', 'dl', ['rye flour'], ['gluten']],
    ['Grahamsmjöl', '🌾', 'dl', ['graham flour'], ['gluten']],
    ['Mandelmjöl', '🌰', 'dl', ['almond flour'], ['nuts']],
    ['Kokosmjöl', '🥥', 'dl', ['coconut flour']],
    ['Glutenfritt mjöl', '🌾', 'dl', ['gluten free flour']],
    ['Vetegluten', '🌾', 'msk', ['vital wheat gluten'], ['gluten']],
    ['Psyllium', '🌱', 'msk', ['psyllium']],
    ['Strösocker', '🍬', 'dl', ['sugar']],
    ['Farinsocker', '🍯', 'dl', ['brown sugar']],
    ['Florsocker', '🍬', 'dl', ['powdered sugar']],
    ['Råsocker', '🍬', 'dl', ['raw sugar']],
    ['Muscovadosocker', '🍯', 'dl', ['muscovado']],
    ['Kokossocker', '🥥', 'dl', ['coconut sugar']],
    ['Pärlsocker', '🍬', 'dl', ['pearl sugar']],
    ['Honung', '🍯', 'msk', ['honey']],
    ['Lönnsirap', '🍯', 'msk', ['maple syrup']],
    ['Agavesirap', '🍯', 'msk', ['agave']],
    ['Ljus sirap', '🍯', 'msk', ['golden syrup']],
    ['Mörk sirap', '🍯', 'msk', ['dark syrup']],
    ['Glukossirap', '🍯', 'msk', ['glucose syrup']],
    ['Stevia', '🍬', 'tsk', ['stevia']],
    ['Erytritol', '🍬', 'tsk', ['erythritol']],
    ['Xylitol', '🍬', 'tsk', ['xylitol']],
    ['Kakao', '🍫', 'msk', ['cocoa']],
    ['Mörk choklad', '🍫', 'g', ['dark chocolate'], ['milk', 'soy']],
    ['Mjölkchoklad', '🍫', 'g', ['milk chocolate'], ['milk', 'soy']],
    ['Vit choklad', '🍫', 'g', ['white chocolate'], ['milk', 'soy']],
    ['Chokladknappar', '🍫', 'dl', ['chocolate chips'], ['milk', 'soy']],
    ['Kakaonibs', '🍫', 'msk', ['cacao nibs']],
    ['Nougat', '🍫', 'g', ['nougat'], ['nuts']],
    ['Nutella', '🍫', 'msk', ['hazelnut spread'], ['nuts', 'milk', 'soy']],
    ['Vaniljsocker', '🍦', 'tsk', ['vanilla sugar']],
    ['Vaniljextrakt', '🍦', 'tsk', ['vanilla extract']],
    ['Mandelmassa', '🌰', 'g', ['almond paste'], ['nuts']],
    ['Marsipan', '🌰', 'g', ['marzipan'], ['nuts']],
    ['Strössel', '🎂', 'msk', ['sprinkles']],
    ['Vinsten', '🧂', 'tsk', ['cream of tartar']],
    ['Citronsyra', '🍋', 'tsk', ['citric acid']],
    ['Invertsocker', '🍯', 'msk', ['invert sugar']],
    ['Dadelsocker', '🍯', 'dl', ['date sugar']],
    ['Bakmargarin', '🧈', 'g', ['baking margarine']],
    ['Tårtbotten', '🎂', 'st', ['sponge base'], ['gluten', 'eggs']],
    ['Vaniljkräm', '🍮', 'dl', ['custard'], ['milk', 'eggs']],
    ['Kola', '🍬', 'g', ['caramel'], ['milk']],
    ['Praliner', '🍫', 'st', ['pralines'], ['nuts', 'milk']],
    ['Fondant', '🎂', 'g', ['fondant']],
    ['Kanderad apelsin', '🍊', 'g', ['candied orange']],
    ['Kanderad citron', '🍋', 'g', ['candied lemon']],
    ['Sockerlag', '🍬', 'dl', ['simple syrup']],
    ['Bakchoklad', '🍫', 'g', ['baking chocolate'], ['milk', 'soy']],
  ],
};
