// Dryck. Tuple: [name, emoji?, defaultUnit?, aliases?, allergens?]
export default {
  category: 'beverages',
  items: [
    ['Apelsinjuice', '🧃', 'dl', ['orange juice']],
    ['Äppeljuice', '🧃', 'dl', ['apple juice']],
    ['Ananasjuice', '🧃', 'dl', ['pineapple juice']],
    ['Tranbärsjuice', '🧃', 'dl', ['cranberry juice']],
    ['Tomatjuice', '🍅', 'dl', ['tomato juice']],
    ['Cola', '🥤', 'dl', ['cola']],
    ['Sockerdricka', '🥤', 'dl', ['lemonade']],
    ['Ingefärsöl', '🥤', 'dl', ['ginger ale']],
    ['Tonic', '🥤', 'dl', ['tonic']],
    ['Sodavatten', '💧', 'dl', ['soda water']],
    ['Mineralvatten', '💧', 'dl', ['sparkling water']],
    ['Kombucha', '🫧', 'dl', ['kombucha']],
    ['Saft', '🧃', 'dl', ['cordial']],
    ['Iste', '🧋', 'dl', ['iced tea']],
    ['Kaffe', '☕', 'dl', ['coffee']],
    ['Espresso', '☕', 'shot', ['espresso']],
    ['Kallbryggt kaffe', '☕', 'dl', ['cold brew']],
    ['Svart te', '🍵', 'dl', ['black tea']],
    ['Grönt te', '🍵', 'dl', ['green tea']],
    ['Matcha', '🍵', 'tsk', ['matcha']],
    ['Chai', '🍵', 'dl', ['chai']],
    ['Varm choklad', '☕', 'dl', ['hot chocolate'], ['milk']],
    ['Havredryck', '🥛', 'dl', ['oat milk'], ['gluten']],
    ['Sojadryck', '🥛', 'dl', ['soy milk'], ['soy']],
    ['Mandeldryck', '🥛', 'dl', ['almond milk'], ['nuts']],
    ['Kokosdryck', '🥥', 'dl', ['coconut milk drink']],
    ['Rödvin', '🍷', 'dl', ['red wine'], ['sulphites']],
    ['Vitt vin', '🍷', 'dl', ['white wine'], ['sulphites']],
    ['Rosévin', '🍷', 'dl', ['rose wine'], ['sulphites']],
    ['Mousserande vin', '🍾', 'dl', ['sparkling wine'], ['sulphites']],
    ['Matlagningsvin', '🍷', 'dl', ['cooking wine'], ['sulphites']],
    ['Glögg', '🍷', 'dl', ['mulled wine'], ['sulphites']],
    ['Ljus öl', '🍺', 'dl', ['lager'], ['gluten']],
    ['Mörk öl', '🍺', 'dl', ['dark beer'], ['gluten']],
    ['Cider', '🍺', 'dl', ['cider'], ['sulphites']],
    ['Madeira', '🍷', 'msk', ['madeira'], ['sulphites']],
    ['Sherry', '🍷', 'msk', ['sherry'], ['sulphites']],
    ['Portvin', '🍷', 'msk', ['port'], ['sulphites']],
    ['Vermouth', '🍸', 'cl', ['vermouth'], ['sulphites']],
    ['Rom', '🥃', 'cl', ['rum']],
    ['Konjak', '🥃', 'cl', ['cognac']],
    ['Vodka', '🍸', 'cl', ['vodka']],
    ['Gin', '🍸', 'cl', ['gin']],
    ['Whisky', '🥃', 'cl', ['whisky']],
    ['Amaretto', '🥃', 'cl', ['amaretto'], ['nuts']],
    ['Baileys', '🥃', 'cl', ['baileys'], ['milk']],
    ['Limoncello', '🍋', 'cl', ['limoncello']],
    ['Energidryck', '🥤', 'dl', ['energy drink']],
    ['Nyponsoppa', '🥣', 'dl', ['rosehip soup']],
    ['Blåbärssoppa', '🥣', 'dl', ['blueberry soup']],
    ['Drickyoghurt', '🥛', 'dl', ['drinking yogurt'], ['milk']],
    ['Aperol', '🍸', 'cl', ['aperol'], ['sulphites']],
    ['Campari', '🍸', 'cl', ['campari'], ['sulphites']],
    ['Triple sec', '🍸', 'cl', ['triple sec']],
    ['Calvados', '🥃', 'cl', ['calvados']],
    ['Grappa', '🥃', 'cl', ['grappa']],
    ['Tequila', '🍸', 'cl', ['tequila']],
    ['Likör', '🥃', 'cl', ['liqueur']],
    ['Punsch', '🥃', 'cl', ['punsch']],
  ],
};
