// Bröd & bageri. Tuple: [name, emoji?, defaultUnit?, aliases?, allergens?]
export default {
  category: 'bread',
  items: [
    ['Baguette', '🥖', 'st', ['baguette'], ['gluten']],
    ['Surdegsbröd', '🍞', 'skiva', ['sourdough'], ['gluten']],
    ['Levain', '🍞', 'skiva', ['levain'], ['gluten']],
    ['Ciabatta', '🍞', 'st', ['ciabatta'], ['gluten']],
    ['Focaccia', '🍞', 'bit', ['focaccia'], ['gluten']],
    ['Grissini', '🥖', 'st', ['grissini'], ['gluten']],
    ['Bagel', '🥯', 'st', ['bagel'], ['gluten']],
    ['Pitabröd', '🥙', 'st', ['pita'], ['gluten']],
    ['Tortilla', '🌯', 'st', ['tortilla', 'wrap'], ['gluten']],
    ['Majstortilla', '🌯', 'st', ['corn tortilla']],
    ['Naan', '🫓', 'st', ['naan'], ['gluten']],
    ['Roti', '🫓', 'st', ['roti'], ['gluten']],
    ['Lavash', '🫓', 'st', ['lavash'], ['gluten']],
    ['Tunnbröd', '🫓', 'st', ['flatbread'], ['gluten']],
    ['Rågbröd', '🍞', 'skiva', ['rye bread'], ['gluten']],
    ['Pumpernickel', '🍞', 'skiva', ['pumpernickel'], ['gluten']],
    ['Fullkornsbröd', '🍞', 'skiva', ['wholegrain bread'], ['gluten']],
    ['Kavring', '🍞', 'skiva', ['kavring'], ['gluten']],
    ['Vörtbröd', '🍞', 'skiva', ['vortbrod'], ['gluten']],
    ['Knäckebröd', '🍘', 'st', ['crispbread'], ['gluten']],
    ['Skorpor', '🍪', 'st', ['rusks'], ['gluten']],
    ['Hamburgerbröd', '🍔', 'st', ['burger bun'], ['gluten']],
    ['Briochebröd', '🍞', 'st', ['brioche bun'], ['gluten', 'milk', 'eggs']],
    ['Korvbröd', '🌭', 'st', ['hot dog bun'], ['gluten']],
    ['Frallor', '🍞', 'st', ['rolls'], ['gluten']],
    ['Croissant', '🥐', 'st', ['croissant'], ['gluten', 'milk']],
    ['Crostini', '🍞', 'st', ['crostini'], ['gluten']],
    ['Krutonger', '🍞', 'dl', ['croutons'], ['gluten']],
    ['Brödsmulor', '🍞', 'dl', ['breadcrumbs'], ['gluten']],
    ['Panko', '🍞', 'dl', ['panko'], ['gluten']],
    ['Ströbröd', '🍞', 'dl', ['breadcrumbs'], ['gluten']],
    ['Pizzabotten', '🍕', 'st', ['pizza base'], ['gluten']],
    ['English muffin', '🍞', 'st', ['english muffin'], ['gluten']],
    ['Pretzel', '🥨', 'st', ['pretzel'], ['gluten']],
    ['Papadum', '🫓', 'st', ['papadum']],
    ['Bao-bröd', '🥟', 'st', ['bao bun'], ['gluten']],
    ['Arepa', '🫓', 'st', ['arepa']],
    ['Injera', '🫓', 'st', ['injera']],
    ['Tortillachips', '🌽', 'g', ['tortilla chips']],
    ['Riskakor', '🍘', 'st', ['rice cakes']],
    ['Sodabread', '🍞', 'skiva', ['soda bread'], ['gluten']],
    ['Hönökaka', '🫓', 'st', ['honokaka'], ['gluten']],
    ['Polarbröd', '🍞', 'st', ['polar bread'], ['gluten']],
    ['Rågkaka', '🍞', 'st', ['rye cake'], ['gluten']],
    ['Baguettini', '🥖', 'st', ['baguettini'], ['gluten']],
    ['Brödchips', '🍞', 'g', ['bread chips'], ['gluten']],
  ],
};
