// Smaksättare & skafferi. Tuple: [name, emoji?, defaultUnit?, aliases?, allergens?]
export default {
  category: 'condiments',
  items: [
    ['Salt', '🧂', 'nypa', ['salt']],
    ['Havssalt', '🧂', 'nypa', ['sea salt']],
    ['Flingsalt', '🧂', 'nypa', ['flake salt']],
    ['Vitlökspulver', '🧄', 'tsk', ['garlic powder']],
    ['Lökpulver', '🧅', 'tsk', ['onion powder']],
    ['Buljongtärning', '🥫', 'st', ['stock cube'], ['celery']],
    ['Grönsaksbuljong', '🥫', 'dl', ['vegetable stock'], ['celery']],
    ['Kycklingbuljong', '🥫', 'dl', ['chicken stock'], ['celery']],
    ['Nötbuljong', '🥫', 'dl', ['beef stock'], ['celery']],
    ['Fiskbuljong', '🥫', 'dl', ['fish stock'], ['fish']],
    ['Dashi', '🥣', 'dl', ['dashi'], ['fish']],
    ['Bonitoflingor', '🐟', 'g', ['bonito flakes'], ['fish']],
    ['Kombu', '🍙', 'g', ['kombu']],
    ['Tomatpuré', '🥫', 'msk', ['tomato paste']],
    ['Krossade tomater', '🥫', 'dl', ['crushed tomatoes']],
    ['Passata', '🥫', 'dl', ['passata']],
    ['Soltorkad tomatpesto', '🥫', 'msk', ['sundried tomato pesto'], ['nuts']],
    ['Kokosmjölk', '🥥', 'dl', ['coconut milk']],
    ['Kokosgrädde', '🥥', 'dl', ['coconut cream']],
    ['Kapris', '🫙', 'msk', ['capers']],
    ['Inlagd jalapeño', '🌶️', 'msk', ['pickled jalapeno']],
    ['Picklad ingefära', '🫚', 'g', ['pickled ginger']],
    ['Ajvar', '🫑', 'msk', ['ajvar']],
    ['Nori', '🍙', 'ark', ['nori', 'seaweed']],
    ['Wakame', '🍙', 'g', ['wakame']],
    ['Misopasta', '🥣', 'msk', ['miso'], ['soy']],
    ['Röd currypasta', '🌶️', 'msk', ['red curry paste']],
    ['Grön currypasta', '🌶️', 'msk', ['green curry paste']],
    ['Tamarindpasta', '🟤', 'msk', ['tamarind paste']],
    ['Mirin', '🍶', 'msk', ['mirin']],
    ['Balsamvinäger', '🍾', 'msk', ['balsamic'], ['sulphites']],
    ['Balsamicokräm', '🍾', 'msk', ['balsamic glaze'], ['sulphites']],
    ['Äppelcidervinäger', '🍾', 'msk', ['apple cider vinegar'], ['sulphites']],
    ['Rödvinsvinäger', '🍾', 'msk', ['red wine vinegar'], ['sulphites']],
    ['Vitvinsvinäger', '🍾', 'msk', ['white wine vinegar'], ['sulphites']],
    ['Risvinäger', '🍾', 'msk', ['rice vinegar']],
    ['Ättika', '🍾', 'msk', ['vinegar']],
    ['Citronsaft', '🍋', 'msk', ['lemon juice']],
    ['Limejuice', '🍋', 'msk', ['lime juice']],
    ['Bakpulver', '🧂', 'tsk', ['baking powder']],
    ['Bikarbonat', '🧂', 'tsk', ['baking soda']],
    ['Torrjäst', '🍞', 'g', ['dry yeast']],
    ['Färsk jäst', '🍞', 'g', ['fresh yeast']],
    ['Majsstärkelse', '🌽', 'msk', ['cornstarch']],
    ['Potatismjöl', '🥔', 'msk', ['potato starch']],
    ['Gelatin', '🍮', 'blad', ['gelatin']],
    ['Agar agar', '🍮', 'tsk', ['agar']],
    ['Pektin', '🍮', 'tsk', ['pectin']],
    ['Flytande rök', '💨', 'tsk', ['liquid smoke']],
    ['Smakförstärkare', '🧂', 'tsk', ['msg']],
    ['Rostad lök', '🧅', 'msk', ['fried onions'], ['gluten']],
    ['Granatäppelmelass', '🥫', 'msk', ['pomegranate molasses']],
    ['Shaoxing', '🍶', 'msk', ['shaoxing wine'], ['sulphites']],
    ['Sake', '🍶', 'msk', ['sake']],
    ['Furikake', '🍙', 'tsk', ['furikake'], ['sesame', 'fish']],
    ['Tsukemono', '🥒', 'g', ['tsukemono']],
    ['Datelssirap', '🍯', 'msk', ['date syrup']],
    ['Rosenvatten', '🌹', 'tsk', ['rose water']],
    ['Apelsinblomvatten', '🍊', 'tsk', ['orange blossom water']],
    ['Xanthangummi', '🧪', 'tsk', ['xanthan gum']],
    ['Masa harina', '🌽', 'dl', ['masa harina']],
    ['Rismjöl', '🍚', 'dl', ['rice flour']],
    ['Kikärtsmjöl', '🫘', 'dl', ['chickpea flour']],
    ['Sojalecitin', '🥫', 'tsk', ['soy lecithin'], ['soy']],
    ['Tapiokastärkelse', '🥫', 'msk', ['tapioca starch']],
  ],
};
