// Mejeri, ost & ägg. Tuple: [name, emoji?, defaultUnit?, aliases?, allergens?]
export default {
  category: 'dairy',
  items: [
    ['Cheddar', '🧀', 'skiva', ['cheddar'], ['milk']],
    ['Mozzarella', '🧀', 'g', ['mozzarella'], ['milk']],
    ['Buffelmozzarella', '🧀', 'g', ['buffalo mozzarella'], ['milk']],
    ['Burrata', '🧀', 'st', ['burrata'], ['milk']],
    ['Parmesan', '🧀', 'g', ['parmesan', 'parmigiano'], ['milk']],
    ['Grana Padano', '🧀', 'g', ['grana padano'], ['milk']],
    ['Pecorino', '🧀', 'g', ['pecorino'], ['milk']],
    ['Fetaost', '🧀', 'g', ['feta'], ['milk']],
    ['Halloumi', '🧀', 'g', ['halloumi'], ['milk']],
    ['Paneer', '🧀', 'g', ['paneer'], ['milk']],
    ['Brie', '🧀', 'skiva', ['brie'], ['milk']],
    ['Camembert', '🧀', 'skiva', ['camembert'], ['milk']],
    ['Gorgonzola', '🧀', 'g', ['gorgonzola', 'blue cheese'], ['milk']],
    ['Roquefort', '🧀', 'g', ['roquefort'], ['milk']],
    ['Ädelost', '🧀', 'g', ['blue cheese'], ['milk']],
    ['Stilton', '🧀', 'g', ['stilton'], ['milk']],
    ['Getost', '🧀', 'g', ['goat cheese', 'chevre'], ['milk']],
    ['Gruyère', '🧀', 'g', ['gruyere'], ['milk']],
    ['Emmentaler', '🧀', 'skiva', ['emmental'], ['milk']],
    ['Gouda', '🧀', 'skiva', ['gouda'], ['milk']],
    ['Edamerost', '🧀', 'skiva', ['edam'], ['milk']],
    ['Comté', '🧀', 'g', ['comte'], ['milk']],
    ['Manchego', '🧀', 'g', ['manchego'], ['milk']],
    ['Provolone', '🧀', 'skiva', ['provolone'], ['milk']],
    ['Taleggio', '🧀', 'g', ['taleggio'], ['milk']],
    ['Raclette', '🧀', 'skiva', ['raclette'], ['milk']],
    ['Jarlsberg', '🧀', 'skiva', ['jarlsberg'], ['milk']],
    ['Havarti', '🧀', 'skiva', ['havarti'], ['milk']],
    ['Asiago', '🧀', 'g', ['asiago'], ['milk']],
    ['Scamorza', '🧀', 'g', ['scamorza'], ['milk']],
    ['Halloumiost', '🧀', 'g', ['grilling cheese'], ['milk']],
    ['Ricotta', '🧀', 'g', ['ricotta'], ['milk']],
    ['Mascarpone', '🧀', 'g', ['mascarpone'], ['milk']],
    ['Keso', '🧀', 'dl', ['cottage cheese'], ['milk']],
    ['Kvarg', '🧀', 'dl', ['quark'], ['milk']],
    ['Skyr', '🥛', 'dl', ['skyr'], ['milk']],
    ['Labneh', '🧀', 'msk', ['labneh'], ['milk']],
    ['Färskost', '🧀', 'msk', ['cream cheese'], ['milk']],
    ['Västerbottensost', '🧀', 'g', ['vasterbotten cheese'], ['milk']],
    ['Prästost', '🧀', 'skiva', ['prastost'], ['milk']],
    ['Herrgårdsost', '🧀', 'skiva', ['herrgard cheese'], ['milk']],
    ['Grevéost', '🧀', 'skiva', ['greve cheese'], ['milk']],
    ['Hushållsost', '🧀', 'skiva', ['hushallsost'], ['milk']],
    ['Mjölk', '🥛', 'dl', ['milk'], ['milk']],
    ['Laktosfri mjölk', '🥛', 'dl', ['lactose free milk'], ['milk']],
    ['Grädde', '🥛', 'dl', ['cream'], ['milk']],
    ['Vispgrädde', '🥛', 'dl', ['whipping cream'], ['milk']],
    ['Matlagningsgrädde', '🥛', 'dl', ['cooking cream'], ['milk']],
    ['Crème fraiche', '🥛', 'msk', ['creme fraiche'], ['milk']],
    ['Gräddfil', '🥛', 'msk', ['sour cream'], ['milk']],
    ['Smetana', '🥛', 'msk', ['smetana'], ['milk']],
    ['Kärnmjölk', '🥛', 'dl', ['buttermilk'], ['milk']],
    ['Kondenserad mjölk', '🥛', 'msk', ['condensed milk'], ['milk']],
    ['Smör', '🧈', 'g', ['butter'], ['milk']],
    ['Brynt smör', '🧈', 'msk', ['brown butter'], ['milk']],
    ['Ghee', '🧈', 'msk', ['ghee'], ['milk']],
    ['Naturell yoghurt', '🥛', 'dl', ['yogurt'], ['milk']],
    ['Turkisk yoghurt', '🥛', 'dl', ['turkish yogurt'], ['milk']],
    ['Grekisk yoghurt', '🥛', 'dl', ['greek yogurt'], ['milk']],
    ['Filmjölk', '🥛', 'dl', ['filmjolk'], ['milk']],
    ['Kefir', '🥛', 'dl', ['kefir'], ['milk']],
    ['Ägg', '🥚', 'st', ['egg'], ['eggs']],
    ['Äggula', '🥚', 'st', ['egg yolk'], ['eggs']],
    ['Äggvita', '🥚', 'st', ['egg white'], ['eggs']],
    ['Vaktelägg', '🥚', 'st', ['quail egg'], ['eggs']],
    ['Fontina', '🧀', 'g', ['fontina'], ['milk']],
    ['Cantal', '🧀', 'g', ['cantal'], ['milk']],
    ['Beaufort', '🧀', 'g', ['beaufort'], ['milk']],
    ['Reblochon', '🧀', 'g', ['reblochon'], ['milk']],
    ['Münsterost', '🧀', 'g', ['munster'], ['milk']],
    ['Morbier', '🧀', 'g', ['morbier'], ['milk']],
    ['Tomme', '🧀', 'g', ['tomme'], ['milk']],
    ['Caciocavallo', '🧀', 'g', ['caciocavallo'], ['milk']],
    ['Stracchino', '🧀', 'g', ['stracchino'], ['milk']],
    ['Robiola', '🧀', 'g', ['robiola'], ['milk']],
    ['Mimolette', '🧀', 'g', ['mimolette'], ['milk']],
    ['Port Salut', '🧀', 'skiva', ['port salut'], ['milk']],
  ],
};
