// Frukt & bär. Tuple: [name, emoji?, defaultUnit?, aliases?, allergens?]
export default {
  category: 'fruit',
  items: [
    ['Äpple', '🍎', 'st', ['apple']],
    ['Granny Smith', '🍏', 'st', ['green apple']],
    ['Päron', '🍐', 'st', ['pear']],
    ['Kvitten', '🍐', 'st', ['quince']],
    ['Banan', '🍌', 'st', ['banana']],
    ['Plantain', '🍌', 'st', ['plantain']],
    ['Apelsin', '🍊', 'st', ['orange']],
    ['Blodapelsin', '🍊', 'st', ['blood orange']],
    ['Clementin', '🍊', 'st', ['clementine']],
    ['Mandarin', '🍊', 'st', ['mandarin']],
    ['Kumquat', '🍊', 'st', ['kumquat']],
    ['Citron', '🍋', 'st', ['lemon']],
    ['Lime', '🍋', 'st', ['lime']],
    ['Grapefrukt', '🍊', 'st', ['grapefruit']],
    ['Pomelo', '🍊', 'st', ['pomelo']],
    ['Yuzu', '🍋', 'st', ['yuzu']],
    ['Bergamott', '🍋', 'st', ['bergamot']],
    ['Mango', '🥭', 'st', ['mango']],
    ['Ananas', '🍍', 'g', ['pineapple']],
    ['Papaya', '🥭', 'g', ['papaya']],
    ['Gröna druvor', '🍇', 'g', ['green grapes']],
    ['Blå druvor', '🍇', 'g', ['grapes']],
    ['Jordgubbar', '🍓', 'g', ['strawberry']],
    ['Smultron', '🍓', 'dl', ['wild strawberry']],
    ['Blåbär', '🫐', 'g', ['blueberry']],
    ['Hallon', '🍓', 'g', ['raspberry']],
    ['Björnbär', '🫐', 'g', ['blackberry']],
    ['Lingon', '🫐', 'dl', ['lingonberry']],
    ['Hjortron', '🫐', 'dl', ['cloudberry']],
    ['Krusbär', '🫐', 'g', ['gooseberry']],
    ['Svarta vinbär', '🫐', 'g', ['blackcurrant']],
    ['Röda vinbär', '🫐', 'g', ['redcurrant']],
    ['Tranbär', '🫐', 'dl', ['cranberry']],
    ['Havtorn', '🫐', 'dl', ['sea buckthorn']],
    ['Aronia', '🫐', 'dl', ['chokeberry']],
    ['Mullbär', '🫐', 'g', ['mulberry']],
    ['Nypon', '🌹', 'dl', ['rosehip']],
    ['Körsbär', '🍒', 'st', ['cherry']],
    ['Granatäpple', '🍎', 'st', ['pomegranate']],
    ['Fikon', '🍈', 'st', ['fig']],
    ['Dadlar', '🍯', 'st', ['dates']],
    ['Russin', '🍇', 'dl', ['raisins'], ['sulphites']],
    ['Aprikos', '🍑', 'st', ['apricot']],
    ['Torkad aprikos', '🍑', 'st', ['dried apricot'], ['sulphites']],
    ['Plommon', '🍑', 'st', ['plum']],
    ['Katrinplommon', '🍑', 'st', ['prune']],
    ['Persika', '🍑', 'st', ['peach']],
    ['Nektarin', '🍑', 'st', ['nectarine']],
    ['Kiwi', '🥝', 'st', ['kiwi']],
    ['Melon', '🍈', 'g', ['melon']],
    ['Cantaloupemelon', '🍈', 'g', ['cantaloupe']],
    ['Honungsmelon', '🍈', 'g', ['honeydew']],
    ['Vattenmelon', '🍉', 'g', ['watermelon']],
    ['Kokos', '🥥', 'g', ['coconut']],
    ['Passionsfrukt', '🍈', 'st', ['passion fruit']],
    ['Lychee', '🍈', 'st', ['lychee']],
    ['Longan', '🍈', 'st', ['longan']],
    ['Rambutan', '🍈', 'st', ['rambutan']],
    ['Mangostan', '🍈', 'st', ['mangosteen']],
    ['Drakfrukt', '🐉', 'st', ['dragon fruit']],
    ['Stjärnfrukt', '⭐', 'st', ['starfruit']],
    ['Guava', '🍈', 'st', ['guava']],
    ['Physalis', '🍈', 'st', ['physalis']],
    ['Kaki', '🍅', 'st', ['persimmon']],
    ['Tamarind', '🟤', 'msk', ['tamarind']],
    ['Jackfruit', '🍈', 'g', ['jackfruit']],
    ['Durian', '🍈', 'g', ['durian']],
    ['Feijoa', '🍈', 'st', ['feijoa']],
    ['Cherimoya', '🍈', 'st', ['cherimoya']],
    ['Gojibär', '🫐', 'msk', ['goji']],
    ['Acaibär', '🫐', 'msk', ['acai']],
    ['Nashipäron', '🍐', 'st', ['nashi pear']],
    ['Galiamelon', '🍈', 'g', ['galia melon']],
    ['Surkörsbär', '🍒', 'st', ['sour cherry', 'morello']],
    ['Bigarråer', '🍒', 'st', ['bigarreau']],
    ['Loganbär', '🫐', 'g', ['loganberry']],
    ['Boysenbär', '🫐', 'g', ['boysenberry']],
    ['Blodgrape', '🍊', 'st', ['ruby grapefruit']],
    ['Sharonfrukt', '🍅', 'st', ['sharon fruit']],
    ['Mirabell', '🍑', 'st', ['mirabelle']],
    ['Saskatoonbär', '🫐', 'g', ['saskatoon']],
  ],
};
