// Spannmål & pasta. Tuple: [name, emoji?, defaultUnit?, aliases?, allergens?]
export default {
  category: 'grains',
  items: [
    ['Spaghetti', '🍝', 'g', ['spaghetti'], ['gluten']],
    ['Penne', '🍝', 'g', ['penne'], ['gluten']],
    ['Fusilli', '🍝', 'g', ['fusilli'], ['gluten']],
    ['Rigatoni', '🍝', 'g', ['rigatoni'], ['gluten']],
    ['Tagliatelle', '🍝', 'g', ['tagliatelle'], ['gluten']],
    ['Linguine', '🍝', 'g', ['linguine'], ['gluten']],
    ['Fettuccine', '🍝', 'g', ['fettuccine'], ['gluten']],
    ['Pappardelle', '🍝', 'g', ['pappardelle'], ['gluten']],
    ['Farfalle', '🍝', 'g', ['farfalle'], ['gluten']],
    ['Conchiglie', '🍝', 'g', ['conchiglie'], ['gluten']],
    ['Cavatappi', '🍝', 'g', ['cavatappi'], ['gluten']],
    ['Bucatini', '🍝', 'g', ['bucatini'], ['gluten']],
    ['Makaroner', '🍝', 'g', ['macaroni'], ['gluten']],
    ['Lasagneplattor', '🍝', 'st', ['lasagne'], ['gluten']],
    ['Cannelloni', '🍝', 'st', ['cannelloni'], ['gluten']],
    ['Ravioli', '🍝', 'st', ['ravioli'], ['gluten', 'eggs']],
    ['Tortellini', '🍝', 'g', ['tortellini'], ['gluten', 'eggs']],
    ['Orzo', '🍝', 'g', ['orzo'], ['gluten']],
    ['Spätzle', '🍝', 'g', ['spatzle'], ['gluten', 'eggs']],
    ['Gnocchi', '🥔', 'g', ['gnocchi'], ['gluten']],
    ['Ris', '🍚', 'dl', ['rice']],
    ['Jasminris', '🍚', 'dl', ['jasmine rice']],
    ['Basmatiris', '🍚', 'dl', ['basmati rice']],
    ['Råris', '🍚', 'dl', ['brown rice']],
    ['Risottoris', '🍚', 'dl', ['arborio', 'risotto']],
    ['Sushiris', '🍚', 'dl', ['sushi rice']],
    ['Vildris', '🍚', 'dl', ['wild rice']],
    ['Quinoa', '🌾', 'dl', ['quinoa']],
    ['Couscous', '🌾', 'dl', ['couscous'], ['gluten']],
    ['Bulgur', '🌾', 'dl', ['bulgur'], ['gluten']],
    ['Freekeh', '🌾', 'dl', ['freekeh'], ['gluten']],
    ['Farro', '🌾', 'dl', ['farro'], ['gluten']],
    ['Matvete', '🌾', 'dl', ['wheat berries'], ['gluten']],
    ['Pärlkorn', '🌾', 'dl', ['pearl barley'], ['gluten']],
    ['Havregryn', '🌾', 'dl', ['oats']],
    ['Hirs', '🌾', 'dl', ['millet']],
    ['Bovete', '🌾', 'dl', ['buckwheat']],
    ['Teff', '🌾', 'dl', ['teff']],
    ['Amarant', '🌾', 'dl', ['amaranth']],
    ['Polenta', '🌽', 'dl', ['polenta']],
    ['Majsmjöl', '🌽', 'dl', ['cornmeal']],
    ['Semolina', '🌾', 'dl', ['semolina'], ['gluten']],
    ['Müsli', '🥣', 'dl', ['muesli'], ['gluten']],
    ['Granola', '🥣', 'dl', ['granola'], ['gluten']],
    ['Cornflakes', '🥣', 'dl', ['cornflakes']],
    ['Nudlar', '🍜', 'g', ['noodles'], ['gluten']],
    ['Äggnudlar', '🍜', 'g', ['egg noodles'], ['gluten', 'eggs']],
    ['Risnudlar', '🍜', 'g', ['rice noodles']],
    ['Glasnudlar', '🍜', 'g', ['glass noodles']],
    ['Udon', '🍜', 'g', ['udon'], ['gluten']],
    ['Ramen', '🍜', 'g', ['ramen'], ['gluten']],
    ['Soba', '🍜', 'g', ['soba']],
    ['Risflingor', '🥣', 'dl', ['rice flakes']],
    ['Havremjöl', '🌾', 'dl', ['oat flour']],
    ['Mannagryn', '🌾', 'dl', ['semolina porridge'], ['gluten']],
    ['Råggryn', '🌾', 'dl', ['rye flakes'], ['gluten']],
    ['Korngryn', '🌾', 'dl', ['barley groats'], ['gluten']],
    ['Dinkelkärnor', '🌾', 'dl', ['spelt berries'], ['gluten']],
    ['Vetekli', '🌾', 'dl', ['wheat bran'], ['gluten']],
    ['Rågflingor', '🌾', 'dl', ['rye rolled'], ['gluten']],
  ],
};
