// Örter & kryddor. Tuple: [name, emoji?, defaultUnit?, aliases?, allergens?]
export default {
  category: 'herbs',
  items: [
    ['Basilika', '🌿', 'nypa', ['basil']],
    ['Thaibasilika', '🌿', 'nypa', ['thai basil']],
    ['Persilja', '🌿', 'nypa', ['parsley']],
    ['Bladpersilja', '🌿', 'nypa', ['flat parsley']],
    ['Koriander', '🌿', 'nypa', ['cilantro', 'coriander']],
    ['Dill', '🌿', 'nypa', ['dill']],
    ['Gräslök', '🌿', 'nypa', ['chives']],
    ['Timjan', '🌿', 'nypa', ['thyme']],
    ['Citrontimjan', '🌿', 'nypa', ['lemon thyme']],
    ['Rosmarin', '🌿', 'kvist', ['rosemary']],
    ['Oregano', '🌿', 'nypa', ['oregano']],
    ['Mejram', '🌿', 'nypa', ['marjoram']],
    ['Salvia', '🌿', 'blad', ['sage']],
    ['Mynta', '🌿', 'nypa', ['mint']],
    ['Pepparmynta', '🌿', 'nypa', ['peppermint']],
    ['Dragon', '🌿', 'nypa', ['tarragon']],
    ['Körvel', '🌿', 'nypa', ['chervil']],
    ['Citronmeliss', '🌿', 'nypa', ['lemon balm']],
    ['Lagerblad', '🌿', 'st', ['bay leaf']],
    ['Libbsticka', '🌿', 'nypa', ['lovage']],
    ['Curryblad', '🌿', 'blad', ['curry leaves']],
    ['Ingefära', '🫚', 'g', ['ginger']],
    ['Galangal', '🫚', 'g', ['galangal']],
    ['Pepparrot', '🌿', 'msk', ['horseradish']],
    ['Citrongräs', '🌿', 'stjälk', ['lemongrass']],
    ['Kaffirlimeblad', '🌿', 'blad', ['kaffir lime']],
    ['Gurkmeja', '🌿', 'tsk', ['turmeric']],
    ['Spiskummin', '🌿', 'tsk', ['cumin']],
    ['Korianderfrö', '🌿', 'tsk', ['coriander seed']],
    ['Fänkålsfrö', '🌿', 'tsk', ['fennel seed']],
    ['Kummin', '🌿', 'tsk', ['caraway']],
    ['Anis', '🌿', 'tsk', ['anise']],
    ['Stjärnanis', '🌟', 'st', ['star anise']],
    ['Paprikapulver', '🌶️', 'tsk', ['paprika']],
    ['Rökt paprikapulver', '🌶️', 'tsk', ['smoked paprika']],
    ['Cayennepeppar', '🌶️', 'tsk', ['cayenne']],
    ['Chilipulver', '🌶️', 'tsk', ['chili powder']],
    ['Chiliflingor', '🌶️', 'nypa', ['chili flakes']],
    ['Chipotle', '🌶️', 'tsk', ['chipotle']],
    ['Ancho', '🌶️', 'st', ['ancho']],
    ['Gochugaru', '🌶️', 'tsk', ['gochugaru']],
    ['Svartpeppar', '🧂', 'nypa', ['black pepper']],
    ['Vitpeppar', '🧂', 'nypa', ['white pepper']],
    ['Grönpeppar', '🧂', 'nypa', ['green peppercorn']],
    ['Rosépeppar', '🧂', 'nypa', ['pink pepper']],
    ['Szechuanpeppar', '🧂', 'nypa', ['sichuan pepper']],
    ['Kanel', '🌿', 'tsk', ['cinnamon']],
    ['Kardemumma', '🌿', 'tsk', ['cardamom']],
    ['Muskotnöt', '🌰', 'nypa', ['nutmeg']],
    ['Kryddnejlika', '🌿', 'st', ['cloves']],
    ['Kryddpeppar', '🌿', 'tsk', ['allspice']],
    ['Vaniljstång', '🌿', 'st', ['vanilla pod']],
    ['Saffran', '🌿', 'g', ['saffron']],
    ['Curry', '🌿', 'tsk', ['curry powder']],
    ['Garam masala', '🌿', 'tsk', ['garam masala']],
    ['Tikka masala', '🌿', 'tsk', ['tikka masala']],
    ['Tandoorikrydda', '🌿', 'tsk', ['tandoori']],
    ['Ras el hanout', '🌿', 'tsk', ['ras el hanout']],
    ['Berbere', '🌿', 'tsk', ['berbere']],
    ['Zaatar', '🌿', 'tsk', ['zaatar'], ['sesame']],
    ['Sumak', '🌿', 'tsk', ['sumac']],
    ['Dukkah', '🌰', 'msk', ['dukkah'], ['nuts', 'sesame']],
    ['Femkryddor', '🌿', 'tsk', ['five spice']],
    ['Togarashi', '🌶️', 'tsk', ['togarashi'], ['sesame']],
    ['Senapsfrö', '🌿', 'tsk', ['mustard seed'], ['mustard']],
    ['Senapspulver', '🌿', 'tsk', ['mustard powder'], ['mustard']],
    ['Bockhornsklöver', '🌿', 'tsk', ['fenugreek']],
    ['Asafoetida', '🌿', 'nypa', ['asafoetida']],
    ['Enbär', '🌿', 'st', ['juniper']],
    ['Herbes de Provence', '🌿', 'tsk', ['herbes de provence']],
    ['Italiensk krydda', '🌿', 'tsk', ['italian seasoning']],
    ['Cajunkrydda', '🌿', 'tsk', ['cajun']],
    ['Jerkkrydda', '🌿', 'tsk', ['jerk']],
    ['Tacokrydda', '🌿', 'tsk', ['taco seasoning']],
    ['Grillkrydda', '🌿', 'tsk', ['bbq rub']],
    ['Citronpeppar', '🧂', 'tsk', ['lemon pepper']],
    ['Örtsalt', '🧂', 'tsk', ['herb salt']],
    ['Vitlökssalt', '🧄', 'tsk', ['garlic salt']],
    ['Sellerisalt', '🧂', 'tsk', ['celery salt'], ['celery']],
    ['Sambal oelek', '🌶️', 'tsk', ['sambal']],
    ['Harissa', '🌶️', 'tsk', ['harissa']],
    ['Torkad oregano', '🌿', 'tsk', ['dried oregano']],
    ['Torkad basilika', '🌿', 'tsk', ['dried basil']],
    ['Torkad timjan', '🌿', 'tsk', ['dried thyme']],
    ['Torkad dill', '🌿', 'tsk', ['dried dill']],
    ['Torkad mynta', '🌿', 'tsk', ['dried mint']],
    ['Pommeskrydda', '🌿', 'tsk', ['fries seasoning']],
    ['Brödkrydda', '🌿', 'tsk', ['bread spice']],
    ['Pepparkakskrydda', '🌿', 'tsk', ['gingerbread spice']],
    ['Glöggkrydda', '🌿', 'tsk', ['mulling spice']],
    ['Fiskkrydda', '🌿', 'tsk', ['fish seasoning']],
    ['Kycklingkrydda', '🌿', 'tsk', ['chicken seasoning']],
    ['Vitlöksgranulat', '🧄', 'tsk', ['granulated garlic']],
    ['Lökgranulat', '🧅', 'tsk', ['granulated onion']],
    ['Rökt salt', '🧂', 'nypa', ['smoked salt']],
    ['Vaniljpulver', '🌿', 'tsk', ['vanilla powder']],
    ['Citronskal', '🍋', 'tsk', ['lemon zest']],
    ['Limeskal', '🍋', 'tsk', ['lime zest']],
    ['Apelsinskal', '🍊', 'tsk', ['orange zest']],
    ['Pepparrotspulver', '🌿', 'tsk', ['horseradish powder']],
    ['Wasabipasta', '🌶️', 'tsk', ['wasabi paste']],
    ['Pickling spice', '🌿', 'tsk', ['pickling spice']],
    ['Adobokrydda', '🌿', 'tsk', ['adobo seasoning']],
  ],
};
