// Baljväxter & vegoprotein. Tuple: [name, emoji?, defaultUnit?, aliases?, allergens?]
export default {
  category: 'legumes',
  items: [
    ['Kikärtor', '🫘', 'dl', ['chickpeas']],
    ['Svarta bönor', '🫘', 'dl', ['black beans']],
    ['Kidneybönor', '🫘', 'dl', ['kidney beans']],
    ['Vita bönor', '🫘', 'dl', ['white beans', 'cannellini']],
    ['Borlottibönor', '🫘', 'dl', ['borlotti']],
    ['Pintobönor', '🫘', 'dl', ['pinto beans']],
    ['Limabönor', '🫘', 'dl', ['lima beans']],
    ['Adzukibönor', '🫘', 'dl', ['adzuki']],
    ['Mungbönor', '🫘', 'dl', ['mung beans']],
    ['Svarta ögonbönor', '🫘', 'dl', ['black eyed peas']],
    ['Röda linser', '🫘', 'dl', ['red lentils']],
    ['Gröna linser', '🫘', 'dl', ['green lentils']],
    ['Puylinser', '🫘', 'dl', ['puy lentils']],
    ['Belugalinser', '🫘', 'dl', ['beluga lentils']],
    ['Gula ärtor', '🫘', 'dl', ['yellow peas']],
    ['Edamame', '🫛', 'dl', ['edamame'], ['soy']],
    ['Sojabönor', '🫘', 'dl', ['soybeans'], ['soy']],
    ['Tofu', '🧈', 'g', ['tofu'], ['soy']],
    ['Rökt tofu', '🧈', 'g', ['smoked tofu'], ['soy']],
    ['Silkestofu', '🧈', 'g', ['silken tofu'], ['soy']],
    ['Tempeh', '🧈', 'g', ['tempeh'], ['soy']],
    ['Seitan', '🍖', 'g', ['seitan'], ['gluten']],
    ['Sojafärs', '🫘', 'g', ['soy mince'], ['soy']],
    ['Sojaprotein', '🫘', 'g', ['tvp'], ['soy']],
    ['Vegofärs', '🫘', 'g', ['plant mince'], ['soy']],
    ['Quorn', '🍗', 'g', ['quorn'], ['eggs']],
    ['Sojanuggets', '🍗', 'st', ['soy nuggets'], ['soy']],
    ['Falafel', '🧆', 'st', ['falafel']],
    ['Hummus', '🫙', 'msk', ['hummus'], ['sesame']],
    ['Lupinbönor', '🫘', 'dl', ['lupin beans'], ['lupin']],
    ['Flageoletbönor', '🫘', 'dl', ['flageolet']],
    ['Cannellinibönor', '🫘', 'dl', ['cannellini']],
    ['Vegobacon', '🥓', 'skiva', ['vegan bacon'], ['soy']],
    ['Vegokorv', '🌭', 'st', ['vegan sausage'], ['soy']],
    ['Ärtprotein', '🫛', 'g', ['pea protein']],
    ['Sojagryn', '🫘', 'g', ['soy grits'], ['soy']],
  ],
};
