// Kött & chark. Tuple: [name, emoji?, defaultUnit?, aliases?, allergens?]
export default {
  category: 'meat',
  items: [
    ['Nötfärs', '🥩', 'g', ['ground beef', 'minced beef']],
    ['Blandfärs', '🥩', 'g', ['mixed mince']],
    ['Fläskfärs', '🥩', 'g', ['ground pork']],
    ['Kalvfärs', '🥩', 'g', ['ground veal']],
    ['Ryggbiff', '🥩', 'g', ['sirloin']],
    ['Entrecôte', '🥩', 'g', ['ribeye', 'entrecote']],
    ['Oxfilé', '🥩', 'g', ['beef tenderloin']],
    ['Flankstek', '🥩', 'g', ['flank steak']],
    ['Högrev', '🥩', 'g', ['chuck']],
    ['Bringa', '🥩', 'g', ['brisket']],
    ['Oxsvans', '🥩', 'g', ['oxtail']],
    ['Oxkind', '🥩', 'g', ['beef cheek']],
    ['Picanha', '🥩', 'g', ['picanha']],
    ['Rostbiff', '🍖', 'skiva', ['roast beef']],
    ['Fläskkarré', '🥩', 'g', ['pork shoulder']],
    ['Fläskfilé', '🥩', 'g', ['pork tenderloin']],
    ['Sidfläsk', '🥩', 'g', ['pork belly']],
    ['Fläsklägg', '🍖', 'g', ['pork knuckle']],
    ['Revben', '🍖', 'g', ['ribs']],
    ['Kassler', '🍖', 'skiva', ['smoked pork loin']],
    ['Bacon', '🥓', 'skiva', ['bacon']],
    ['Bacontärningar', '🥓', 'g', ['bacon bits']],
    ['Pancetta', '🥓', 'g', ['pancetta']],
    ['Guanciale', '🥓', 'g', ['guanciale']],
    ['Lardo', '🥓', 'skiva', ['lardo']],
    ['Kokt skinka', '🍖', 'skiva', ['cooked ham']],
    ['Rökt skinka', '🍖', 'skiva', ['smoked ham']],
    ['Lufttorkad skinka', '🍖', 'skiva', ['prosciutto']],
    ['Serranoskinka', '🍖', 'skiva', ['serrano']],
    ['Bresaola', '🍖', 'skiva', ['bresaola']],
    ['Salami', '🍖', 'skiva', ['salami']],
    ['Chorizo', '🌭', 'g', ['chorizo']],
    ['Saltchorizo', '🌭', 'skiva', ['cured chorizo']],
    ['Mortadella', '🍖', 'skiva', ['mortadella'], ['nuts']],
    ['Coppa', '🍖', 'skiva', ['coppa']],
    ['Speck', '🍖', 'skiva', ['speck']],
    ['Nduja', '🌶️', 'msk', ['nduja']],
    ['Korv', '🌭', 'st', ['sausage']],
    ['Bratwurst', '🌭', 'st', ['bratwurst']],
    ['Salsiccia', '🌭', 'st', ['salsiccia']],
    ['Merguez', '🌭', 'st', ['merguez']],
    ['Wienerkorv', '🌭', 'st', ['wiener']],
    ['Falukorv', '🌭', 'skiva', ['falukorv']],
    ['Prinskorv', '🌭', 'st', ['cocktail sausage']],
    ['Isterband', '🌭', 'st', ['isterband']],
    ['Köttbullar', '🍖', 'st', ['meatballs']],
    ['Pulled pork', '🍖', 'g', ['pulled pork']],
    ['Pastrami', '🍖', 'skiva', ['pastrami']],
    ['Lammfärs', '🥩', 'g', ['ground lamb']],
    ['Lammracks', '🍖', 'st', ['rack of lamb']],
    ['Lammstek', '🍖', 'g', ['leg of lamb']],
    ['Lammkotlett', '🍖', 'st', ['lamb chop']],
    ['Lammbog', '🍖', 'g', ['lamb shoulder']],
    ['Renskav', '🦌', 'g', ['reindeer']],
    ['Älgfärs', '🦌', 'g', ['moose']],
    ['Hjortkött', '🦌', 'g', ['venison']],
    ['Vildsvin', '🐗', 'g', ['wild boar']],
    ['Anklever', '🦆', 'g', ['foie gras']],
    ['Blodpudding', '🍖', 'skiva', ['black pudding']],
    ['Leverpastej', '🍖', 'msk', ['liver pate']],
    ['Skinkstek', '🍖', 'g', ['ham roast']],
    ['Märgben', '🦴', 'st', ['marrow bone']],
    ['Soppben', '🦴', 'st', ['soup bone']],
    ['Fläskkotlett', '🍖', 'st', ['pork chop']],
    ['Bogfläsk', '🥩', 'g', ['pork collar']],
    ['Karbonad', '🍖', 'st', ['pork patty']],
    ['Flintastek', '🍖', 'st', ['marinated pork steak']],
    ['Kebabkött', '🥙', 'g', ['kebab meat']],
    ['Gyroskött', '🥙', 'g', ['gyros']],
    ['Pulled beef', '🍖', 'g', ['pulled beef']],
  ],
};
