// Svamp. Tuple: [name, emoji?, defaultUnit?, aliases?, allergens?]
export default {
  category: 'mushrooms',
  items: [
    ['Champinjoner', '🍄', 'g', ['mushrooms', 'button mushroom']],
    ['Kastanjchampinjon', '🍄', 'g', ['chestnut mushroom', 'cremini']],
    ['Portabello', '🍄', 'st', ['portobello']],
    ['Kantareller', '🍄', 'g', ['chanterelles']],
    ['Trattkantarell', '🍄', 'g', ['funnel chanterelle']],
    ['Karljohan', '🍄', 'g', ['porcini', 'cep']],
    ['Smörsopp', '🍄', 'g', ['bolete']],
    ['Shiitake', '🍄', 'g', ['shiitake']],
    ['Ostronskivling', '🍄', 'g', ['oyster mushroom']],
    ['Kungsostronskivling', '🍄', 'st', ['king oyster']],
    ['Enoki', '🍄', 'g', ['enoki']],
    ['Shimeji', '🍄', 'g', ['shimeji']],
    ['Maitake', '🍄', 'g', ['maitake']],
    ['Igelkottstaggsvamp', '🍄', 'g', ['lions mane']],
    ['Tryffel', '🍄', 'g', ['truffle']],
    ['Svart tryffel', '🍄', 'g', ['black truffle']],
    ['Murklor', '🍄', 'g', ['morels']],
    ['Blandsvamp', '🍄', 'g', ['mixed mushrooms']],
    ['Torkad svamp', '🍄', 'g', ['dried mushrooms']],
    ['Svartriska', '🍄', 'g', ['saffron milk cap']],
    ['Trumpetsvamp', '🍄', 'g', ['black trumpet']],
    ['Nameko', '🍄', 'g', ['nameko']],
    ['Vit tryffel', '🍄', 'g', ['white truffle']],
  ],
};
