// Nötter & frön. Tuple: [name, emoji?, defaultUnit?, aliases?, allergens?]
export default {
  category: 'nuts',
  items: [
    ['Mandel', '🌰', 'g', ['almonds'], ['nuts']],
    ['Flagad mandel', '🌰', 'msk', ['flaked almonds'], ['nuts']],
    ['Valnötter', '🌰', 'g', ['walnuts'], ['nuts']],
    ['Cashewnötter', '🥜', 'g', ['cashews'], ['nuts']],
    ['Hasselnötter', '🌰', 'g', ['hazelnuts'], ['nuts']],
    ['Pinjenötter', '🌰', 'msk', ['pine nuts'], ['nuts']],
    ['Pistage', '🥜', 'g', ['pistachio'], ['nuts']],
    ['Pekannötter', '🌰', 'g', ['pecans'], ['nuts']],
    ['Paranötter', '🌰', 'g', ['brazil nuts'], ['nuts']],
    ['Macadamianötter', '🌰', 'g', ['macadamia'], ['nuts']],
    ['Jordnötter', '🥜', 'g', ['peanuts'], ['peanuts']],
    ['Kokosflingor', '🥥', 'dl', ['coconut flakes']],
    ['Kokoschips', '🥥', 'dl', ['coconut chips']],
    ['Cashewsmör', '🥜', 'msk', ['cashew butter'], ['nuts']],
    ['Mandelsmör', '🥜', 'msk', ['almond butter'], ['nuts']],
    ['Jordnötssmör', '🥜', 'msk', ['peanut butter'], ['peanuts']],
    ['Solrosfrön', '🌻', 'msk', ['sunflower seeds']],
    ['Pumpafrön', '🎃', 'msk', ['pumpkin seeds']],
    ['Sesamfrön', '🌰', 'msk', ['sesame seeds'], ['sesame']],
    ['Svarta sesamfrön', '🌰', 'msk', ['black sesame'], ['sesame']],
    ['Chiafrön', '🌱', 'msk', ['chia seeds']],
    ['Linfrön', '🌱', 'msk', ['flax seeds']],
    ['Hampafrön', '🌱', 'msk', ['hemp seeds']],
    ['Vallmofrön', '🌱', 'msk', ['poppy seeds']],
    ['Tigernötter', '🌰', 'g', ['tiger nuts']],
    ['Kastanjer', '🌰', 'g', ['chestnuts']],
    ['Solrosfröpasta', '🌻', 'msk', ['sunflower butter']],
    ['Hampaprotein', '🌱', 'msk', ['hemp protein']],
    ['Cashewbitar', '🥜', 'g', ['cashew pieces'], ['nuts']],
    ['Hasselnötspasta', '🌰', 'msk', ['hazelnut butter'], ['nuts']],
  ],
};
