// Såser & dressing. Tuple: [name, emoji?, defaultUnit?, aliases?, allergens?]
export default {
  category: 'sauces',
  items: [
    ['Tomatsås', '🥫', 'dl', ['tomato sauce']],
    ['Pizzasås', '🥫', 'dl', ['pizza sauce']],
    ['Marinarasås', '🥫', 'dl', ['marinara']],
    ['Arrabiatasås', '🥫', 'dl', ['arrabiata']],
    ['Bolognese', '🥫', 'dl', ['bolognese']],
    ['Carbonarasås', '🥫', 'dl', ['carbonara'], ['milk', 'eggs']],
    ['Alfredosås', '🥫', 'dl', ['alfredo'], ['milk']],
    ['Pesto', '🥫', 'msk', ['pesto'], ['nuts', 'milk']],
    ['Röd pesto', '🥫', 'msk', ['red pesto'], ['nuts', 'milk']],
    ['Béchamelsås', '🥫', 'dl', ['bechamel'], ['milk', 'gluten']],
    ['Béarnaisesås', '🥫', 'dl', ['bearnaise'], ['eggs', 'milk']],
    ['Hollandaisesås', '🥫', 'dl', ['hollandaise'], ['eggs', 'milk']],
    ['Aioli', '🧄', 'msk', ['aioli'], ['eggs']],
    ['Vitlökssås', '🧄', 'msk', ['garlic sauce'], ['eggs']],
    ['Sweet chilisås', '🌶️', 'msk', ['sweet chili']],
    ['Sojasås', '🥫', 'msk', ['soy sauce'], ['soy', 'gluten']],
    ['Ljus soja', '🥫', 'msk', ['light soy'], ['soy', 'gluten']],
    ['Mörk soja', '🥫', 'msk', ['dark soy'], ['soy', 'gluten']],
    ['Teriyakisås', '🥫', 'msk', ['teriyaki'], ['soy', 'gluten']],
    ['Ponzu', '🥫', 'msk', ['ponzu'], ['soy', 'fish']],
    ['Sriracha', '🌶️', 'tsk', ['sriracha']],
    ['Gochujang', '🌶️', 'msk', ['gochujang'], ['soy']],
    ['BBQ-sås', '🥫', 'msk', ['bbq sauce']],
    ['Ketchup', '🍅', 'msk', ['ketchup']],
    ['Dijonsenap', '🌭', 'tsk', ['dijon'], ['mustard']],
    ['Grovkornig senap', '🌭', 'tsk', ['wholegrain mustard'], ['mustard']],
    ['Sötstark senap', '🌭', 'tsk', ['sweet mustard'], ['mustard']],
    ['Majonnäs', '🥫', 'msk', ['mayonnaise', 'mayo'], ['eggs']],
    ['Rhode Island', '🥫', 'msk', ['rhode island'], ['eggs']],
    ['Tartarsås', '🥫', 'msk', ['tartar sauce'], ['eggs']],
    ['Remouladsås', '🥫', 'msk', ['remoulade'], ['eggs']],
    ['Cocktailsås', '🥫', 'msk', ['cocktail sauce'], ['eggs']],
    ['Ranchdressing', '🥫', 'msk', ['ranch'], ['eggs', 'milk']],
    ['Caesardressing', '🥫', 'msk', ['caesar dressing'], ['eggs', 'fish', 'milk']],
    ['Vinägrett', '🥫', 'msk', ['vinaigrette']],
    ['Tzatziki', '🥒', 'msk', ['tzatziki'], ['milk']],
    ['Raita', '🥒', 'msk', ['raita'], ['milk']],
    ['Salsa', '🍅', 'msk', ['salsa']],
    ['Pico de gallo', '🍅', 'msk', ['pico de gallo']],
    ['Guacamole', '🥑', 'msk', ['guacamole']],
    ['Chimichurri', '🌿', 'msk', ['chimichurri']],
    ['Romesco', '🥫', 'msk', ['romesco'], ['nuts']],
    ['Babaganoush', '🍆', 'msk', ['baba ganoush'], ['sesame']],
    ['Fisksås', '🐟', 'tsk', ['fish sauce'], ['fish']],
    ['Ostronsås', '🦪', 'msk', ['oyster sauce'], ['molluscs']],
    ['Hoisinsås', '🥫', 'msk', ['hoisin'], ['soy', 'gluten']],
    ['Worcestershiresås', '🥫', 'tsk', ['worcestershire'], ['fish']],
    ['Tahini', '🥫', 'msk', ['tahini'], ['sesame']],
    ['Jordnötssås', '🥜', 'msk', ['peanut sauce'], ['peanuts']],
    ['Satay', '🥜', 'msk', ['satay'], ['peanuts']],
    ['Currysås', '🥫', 'dl', ['curry sauce']],
    ['Kormasås', '🥫', 'dl', ['korma'], ['nuts', 'milk']],
    ['Brunsås', '🥫', 'dl', ['gravy'], ['gluten']],
    ['Skagenröra', '🦐', 'msk', ['skagen'], ['crustaceans', 'eggs']],
    ['Mango chutney', '🥭', 'msk', ['mango chutney']],
    ['Tonkatsusås', '🥫', 'msk', ['tonkatsu'], ['soy', 'gluten']],
    ['Sweet & sour', '🥫', 'msk', ['sweet and sour']],
    ['Black bean-sås', '🥫', 'msk', ['black bean sauce'], ['soy']],
    ['Plommonsås', '🥫', 'msk', ['plum sauce']],
    ['Enchiladasås', '🌶️', 'dl', ['enchilada sauce']],
    ['Pad thai-sås', '🥫', 'msk', ['pad thai sauce'], ['fish', 'peanuts']],
    ['Yakitorisås', '🥫', 'msk', ['yakitori'], ['soy', 'gluten']],
    ['Katsusås', '🥫', 'msk', ['katsu sauce'], ['soy', 'gluten']],
    ['Mole', '🥫', 'dl', ['mole'], ['nuts']],
    ['Adobosås', '🌶️', 'msk', ['adobo']],
    ['Vindaloosås', '🌶️', 'dl', ['vindaloo']],
    ['Pepparrotssås', '🥫', 'msk', ['horseradish sauce'], ['milk']],
    ['Dillsås', '🥫', 'msk', ['dill sauce'], ['milk']],
    ['Hovmästarsås', '🥫', 'msk', ['mustard dill sauce'], ['mustard']],
    ['XO-sås', '🥫', 'msk', ['xo sauce'], ['crustaceans', 'fish']],
    ['Muhammara', '🌶️', 'msk', ['muhammara'], ['nuts']],
    ['Nuoc cham', '🥫', 'msk', ['nuoc cham'], ['fish']],
    ['Tikka masala-sås', '🥫', 'dl', ['tikka masala sauce'], ['milk']],
  ],
};
