// Fisk & skaldjur. Tuple: [name, emoji?, defaultUnit?, aliases?, allergens?]
export default {
  category: 'seafood',
  items: [
    ['Lax', '🐟', 'g', ['salmon'], ['fish']],
    ['Rökt lax', '🐟', 'g', ['smoked salmon'], ['fish']],
    ['Gravad lax', '🐟', 'g', ['cured salmon'], ['fish']],
    ['Regnbågslax', '🐟', 'g', ['rainbow trout'], ['fish']],
    ['Torsk', '🐟', 'g', ['cod'], ['fish']],
    ['Sej', '🐟', 'g', ['saithe'], ['fish']],
    ['Kolja', '🐟', 'g', ['haddock'], ['fish']],
    ['Kummel', '🐟', 'g', ['hake'], ['fish']],
    ['Pollock', '🐟', 'g', ['pollock'], ['fish']],
    ['Tonfisk', '🐟', 'g', ['tuna'], ['fish']],
    ['Sashimi-tonfisk', '🐟', 'g', ['sashimi tuna'], ['fish']],
    ['Svärdfisk', '🐟', 'g', ['swordfish'], ['fish']],
    ['Sill', '🐟', 'g', ['herring'], ['fish']],
    ['Inlagd sill', '🐟', 'bit', ['pickled herring'], ['fish']],
    ['Strömming', '🐟', 'st', ['baltic herring'], ['fish']],
    ['Makrill', '🐟', 'g', ['mackerel'], ['fish']],
    ['Rökt makrill', '🐟', 'g', ['smoked mackerel'], ['fish']],
    ['Sardiner', '🐟', 'st', ['sardines'], ['fish']],
    ['Ansjovis', '🐟', 'st', ['anchovy'], ['fish']],
    ['Hälleflundra', '🐟', 'g', ['halibut'], ['fish']],
    ['Rödspätta', '🐟', 'g', ['plaice'], ['fish']],
    ['Sjötunga', '🐟', 'g', ['sole'], ['fish']],
    ['Piggvar', '🐟', 'g', ['turbot'], ['fish']],
    ['Havsabborre', '🐟', 'g', ['sea bass'], ['fish']],
    ['Havsruda', '🐟', 'g', ['sea bream'], ['fish']],
    ['Röding', '🐟', 'g', ['arctic char'], ['fish']],
    ['Gös', '🐟', 'g', ['pike perch'], ['fish']],
    ['Abborre', '🐟', 'g', ['perch'], ['fish']],
    ['Sik', '🐟', 'g', ['whitefish'], ['fish']],
    ['Marulk', '🐟', 'g', ['monkfish'], ['fish']],
    ['Tilapia', '🐟', 'g', ['tilapia'], ['fish']],
    ['Pangasius', '🐟', 'g', ['pangasius'], ['fish']],
    ['Ål', '🐟', 'g', ['eel'], ['fish']],
    ['Fiskrom', '🐟', 'msk', ['roe'], ['fish']],
    ['Löjrom', '🐟', 'msk', ['vendace roe'], ['fish']],
    ['Kaviar', '🐟', 'msk', ['caviar'], ['fish']],
    ['Räkor', '🦐', 'g', ['shrimp', 'prawns'], ['crustaceans']],
    ['Handskalade räkor', '🦐', 'g', ['peeled shrimp'], ['crustaceans']],
    ['Tigerräkor', '🦐', 'st', ['tiger prawns'], ['crustaceans']],
    ['Scampi', '🦐', 'st', ['scampi'], ['crustaceans']],
    ['Kräftor', '🦞', 'st', ['crayfish'], ['crustaceans']],
    ['Krabba', '🦀', 'g', ['crab'], ['crustaceans']],
    ['Krabbklor', '🦀', 'st', ['crab claws'], ['crustaceans']],
    ['Kungskrabba', '🦀', 'g', ['king crab'], ['crustaceans']],
    ['Hummer', '🦞', 'st', ['lobster'], ['crustaceans']],
    ['Havskräfta', '🦞', 'st', ['langoustine'], ['crustaceans']],
    ['Blåmusslor', '🦪', 'g', ['mussels'], ['molluscs']],
    ['Ostron', '🦪', 'st', ['oysters'], ['molluscs']],
    ['Pilgrimsmusslor', '🦪', 'st', ['scallops'], ['molluscs']],
    ['Vongole', '🦪', 'g', ['clams'], ['molluscs']],
    ['Hjärtmusslor', '🦪', 'g', ['cockles'], ['molluscs']],
    ['Bläckfisk', '🦑', 'g', ['squid', 'calamari'], ['molluscs']],
    ['Åttaarmad bläckfisk', '🐙', 'g', ['octopus'], ['molluscs']],
    ['Sjöborre', '🦪', 'st', ['sea urchin'], ['molluscs']],
    ['Surimi', '🦀', 'st', ['surimi'], ['fish', 'crustaceans']],
    ['Forell', '🐟', 'g', ['trout'], ['fish']],
    ['Havskatt', '🐟', 'g', ['wolffish'], ['fish']],
    ['Rödtunga', '🐟', 'g', ['lemon sole'], ['fish']],
    ['Lubb', '🐟', 'g', ['cusk'], ['fish']],
    ['Sardeller', '🐟', 'st', ['anchovies'], ['fish']],
    ['Stenbitsrom', '🐟', 'msk', ['lumpfish roe'], ['fish']],
    ['Musselkött', '🦪', 'g', ['mussel meat'], ['molluscs']],
    ['Smörfisk', '🐟', 'g', ['butterfish'], ['fish']],
  ],
};
