// Grönsaker. Tuple: [name, emoji?, defaultUnit?, aliases?, allergens?]
export default {
  category: 'vegetables',
  items: [
    ['Tomat', '🍅', 'st', ['tomato']],
    ['Bifftomat', '🍅', 'skiva', ['beef tomato']],
    ['Körsbärstomat', '🍅', 'st', ['cherry tomato']],
    ['Cocktailtomat', '🍅', 'st'],
    ['Plommontomat', '🍅', 'st', ['plum tomato']],
    ['San Marzano-tomat', '🍅', 'st'],
    ['Gröna tomater', '🍅', 'st', ['green tomato']],
    ['Soltorkad tomat', '🍅', 'g', ['sundried tomato']],
    ['Gurka', '🥒', 'skiva', ['cucumber']],
    ['Cornichon', '🥒', 'st', ['cornichon']],
    ['Inlagd gurka', '🥒', 'skiva', ['pickles']],
    ['Isbergssallad', '🥬', 'blad', ['iceberg lettuce']],
    ['Romansallad', '🥬', 'blad', ['romaine']],
    ['Ekbladssallad', '🥬', 'blad', ['oak leaf']],
    ['Frisésallad', '🥬', 'blad', ['frisee']],
    ['Mâchesallad', '🥬', 'g', ['lambs lettuce']],
    ['Babyleaf', '🥬', 'g', ['baby leaf']],
    ['Ruccola', '🌿', 'g', ['rocket', 'arugula']],
    ['Vattenkrasse', '🌿', 'g', ['watercress']],
    ['Mizuna', '🌿', 'g', ['mizuna']],
    ['Babyspenat', '🥬', 'g', ['baby spinach']],
    ['Bladspenat', '🥬', 'g', ['spinach']],
    ['Mangold', '🥬', 'blad', ['chard']],
    ['Grönkål', '🥬', 'g', ['kale']],
    ['Svartkål', '🥬', 'g', ['cavolo nero']],
    ['Vitkål', '🥬', 'g', ['white cabbage']],
    ['Spetskål', '🥬', 'g', ['pointed cabbage']],
    ['Rödkål', '🥬', 'g', ['red cabbage']],
    ['Savojkål', '🥬', 'g', ['savoy cabbage']],
    ['Salladskål', '🥬', 'g', ['napa cabbage']],
    ['Blomkål', '🥦', 'g', ['cauliflower']],
    ['Broccoli', '🥦', 'g', ['broccoli']],
    ['Broccolini', '🥦', 'g', ['broccolini']],
    ['Romanesco', '🥦', 'g', ['romanesco']],
    ['Brysselkål', '🥬', 'g', ['brussels sprouts']],
    ['Kålrabbi', '🥬', 'g', ['kohlrabi']],
    ['Morot', '🥕', 'g', ['carrot']],
    ['Babymorot', '🥕', 'st', ['baby carrot']],
    ['Rödbeta', '🫐', 'g', ['beetroot']],
    ['Gul beta', '🫐', 'g', ['golden beet']],
    ['Polkabeta', '🫐', 'g', ['chioggia beet']],
    ['Inlagd rödbeta', '🫐', 'skiva', ['pickled beetroot']],
    ['Palsternacka', '🥕', 'g', ['parsnip']],
    ['Rättika', '🌶️', 'g', ['daikon', 'mooli']],
    ['Rädisa', '🌶️', 'st', ['radish']],
    ['Kålrot', '🥬', 'g', ['swede', 'rutabaga']],
    ['Majrova', '🥬', 'g', ['turnip']],
    ['Jordärtskocka', '🥔', 'g', ['jerusalem artichoke']],
    ['Kronärtskocka', '🌿', 'st', ['artichoke']],
    ['Grön sparris', '🥬', 'st', ['green asparagus']],
    ['Vit sparris', '🥬', 'st', ['white asparagus']],
    ['Selleri', '🥬', 'stjälk', ['celery'], ['celery']],
    ['Rotselleri', '🥬', 'g', ['celeriac'], ['celery']],
    ['Fänkål', '🌿', 'g', ['fennel']],
    ['Purjolök', '🥬', 'g', ['leek']],
    ['Gul lök', '🧅', 'g', ['onion', 'yellow onion']],
    ['Röd lök', '🧅', 'ring', ['red onion']],
    ['Vit lök', '🧅', 'g', ['white onion']],
    ['Silverlök', '🧅', 'st', ['pearl onion']],
    ['Salladslök', '🌿', 'st', ['spring onion', 'scallion']],
    ['Schalottenlök', '🧅', 'st', ['shallot']],
    ['Picklad rödlök', '🧅', 'g', ['pickled red onion']],
    ['Vitlök', '🧄', 'klyfta', ['garlic']],
    ['Svart vitlök', '🧄', 'klyfta', ['black garlic']],
    ['Ramslök', '🌿', 'g', ['wild garlic']],
    ['Röd paprika', '🫑', 'g', ['red bell pepper']],
    ['Gul paprika', '🫑', 'g', ['yellow pepper']],
    ['Grön paprika', '🫑', 'g', ['green pepper']],
    ['Spetspaprika', '🫑', 'st', ['romano pepper']],
    ['Rostad paprika', '🫑', 'g', ['roasted pepper']],
    ['Padrón', '🌶️', 'st', ['padron']],
    ['Chilipeppar', '🌶️', 'st', ['chili']],
    ['Habanero', '🌶️', 'st', ['habanero']],
    ['Jalapeño', '🌶️', 'st', ['jalapeno']],
    ['Birdeye-chili', '🌶️', 'st', ['birds eye chili']],
    ['Poblano', '🌶️', 'st', ['poblano']],
    ['Scotch bonnet', '🌶️', 'st', ['scotch bonnet']],
    ['Aubergine', '🍆', 'g', ['eggplant', 'aubergine']],
    ['Zucchini', '🥒', 'g', ['zucchini', 'courgette']],
    ['Squash', '🥒', 'g', ['squash']],
    ['Pumpa', '🎃', 'g', ['pumpkin']],
    ['Butternutpumpa', '🎃', 'g', ['butternut squash']],
    ['Muskatpumpa', '🎃', 'g'],
    ['Spaghettisquash', '🎃', 'g', ['spaghetti squash']],
    ['Patisson', '🎃', 'st'],
    ['Majs', '🌽', 'dl', ['corn', 'sweetcorn']],
    ['Babymajs', '🌽', 'st', ['baby corn']],
    ['Ärtor', '🫛', 'dl', ['peas']],
    ['Sockerärter', '🫛', 'g', ['sugar snap']],
    ['Haricots verts', '🫛', 'g', ['green beans']],
    ['Brytbönor', '🫛', 'g', ['string beans']],
    ['Vaxbönor', '🫛', 'g', ['wax beans']],
    ['Bondbönor', '🫛', 'dl', ['fava beans', 'broad beans']],
    ['Avokado', '🥑', 'st', ['avocado']],
    ['Potatis', '🥔', 'g', ['potato']],
    ['Färskpotatis', '🥔', 'g', ['new potato']],
    ['Bakpotatis', '🥔', 'st', ['baking potato']],
    ['Mandelpotatis', '🥔', 'g'],
    ['Sötpotatis', '🍠', 'g', ['sweet potato']],
    ['Okra', '🥬', 'st', ['okra']],
    ['Bambuskott', '🥬', 'g', ['bamboo shoots']],
    ['Vattenkastanj', '🥬', 'g', ['water chestnut']],
    ['Böngroddar', '🌱', 'g', ['bean sprouts']],
    ['Alfalfagroddar', '🌱', 'g', ['alfalfa']],
    ['Ärtskott', '🌱', 'g', ['pea shoots']],
    ['Endiv', '🥬', 'blad', ['endive']],
    ['Radicchio', '🥬', 'blad', ['radicchio']],
    ['Rabarber', '🌿', 'stjälk', ['rhubarb']],
    ['Tomatillo', '🍅', 'st', ['tomatillo']],
    ['Chayote', '🥒', 'st', ['chayote']],
    ['Lotusrot', '🥬', 'g', ['lotus root']],
    ['Kassava', '🥔', 'g', ['cassava', 'manioc']],
    ['Taro', '🥔', 'g', ['taro']],
    ['Yamsrot', '🍠', 'g', ['yam']],
    ['Gröna oliver', '🫒', 'st', ['green olives']],
    ['Svarta oliver', '🫒', 'st', ['black olives']],
    ['Kalamataoliver', '🫒', 'st', ['kalamata']],
    ['Surkål', '🥬', 'g', ['sauerkraut']],
    ['Kimchi', '🥬', 'g', ['kimchi']],
    ['Pak choi', '🥬', 'st', ['bok choy', 'pak choi']],
    ['Pepperoncini', '🌶️', 'st', ['pepperoncini']],
    ['Shishitopaprika', '🌶️', 'st', ['shishito']],
    ['Serranochili', '🌶️', 'st', ['serrano']],
    ['Fresnochili', '🌶️', 'st', ['fresno']],
    ['Anaheimchili', '🌶️', 'st', ['anaheim']],
    ['Svartrot', '🥬', 'g', ['salsify']],
    ['Rotpersilja', '🥕', 'g', ['parsley root']],
    ['Microgreens', '🌱', 'g', ['microgreens']],
    ['Salladsmix', '🥬', 'g', ['salad mix']],
    ['Wokgrönsaker', '🥬', 'g', ['stir fry vegetables']],
    ['Strimlad vitkål', '🥬', 'g', ['shredded cabbage']],
    ['Groddmix', '🌱', 'g', ['sprout mix']],
    ['Rotfruktsmix', '🥕', 'g', ['root vegetable mix']],
  ],
};
